project_id = "securedrop-dev"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
[db]
port = 54322
shadow_port = 54323
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/**"]

[storage]
file_size_limit = "100MB"

[analytics]
enabled = false
